### ISSUE TITLE
终端无法加载build.sh文件

### ISSUE THREAD

**Issue by YEZENING** [xioxin/biliATV#10]
<img width="790" alt="screen shot 2018-01-24 at 21 14 27" src="https://user-images.githubusercontent.com/24925677/35367315-c19db230-014b-11e8-973b-2983b4a3ed11.png">

就在biliATV根目录下可是不知道为什么无法加载

**Comment by xioxin** [comment]
先 cd到 biliATV目录下 再执行 sh build.sh 
不要直接执行

**Comment by YEZENING** [comment]
我已经用cd进入了可还是和刚刚现象差不多
<img width="1038" alt="screen shot 2018-01-24 at 21 36 36" src="https://user-images.githubusercontent.com/24925677/35367905-cc614300-014e-11e8-9865-207207c6a65f.png">

**Comment by xioxin** [comment]
删掉现在的 
直接执行
```
git clone https://github.com/xioxin/biliATV.git
cd biliATV && sh build.sh
```

**Comment by YEZENING** [comment]
表示安装成功十分感谢！！
