### ISSUE TITLE
Error Launching Application

### ISSUE THREAD

**Issue by kokoroX** [xioxin/biliATV#14]
TV version
Apple TV 4K/tvOS 11.2.1

真机调试版本报
Error Launching Application
The operation couldn't be completed.(TVMLKitErrorDomain error 3.)

真机调试的时候把tvBaseURL改成本地起的服务器就不会有这个问题 不过进app之后的内容出现问题
模拟器调试的时候不改tvBaseURL也没有任何问题 进app之后的内容也正常

求助

**Comment by xioxin** [comment]
代码放在 https://coding.net/u/xin/p/biliATV/git/raw/master/TVML/application.js 
你看下能访问吗

**Comment by xioxin** [comment]
你可以尝试修改为  https://raw.githubusercontent.com/xioxin/biliATV/master/TVML/application.js

**Comment by kokoroX** [comment]
@xioxin dns改成手动的好了...谢谢耐心解答
