### ISSUE TITLE
视频无法暂停及调整播放进度

### ISSUE THREAD

**Issue by byuan04** [xioxin/biliATV#15]
更新到1.26提交的 291e974 版本后，无法暂停

按触摸板暂停，和暂停按钮均无效。 
会出现下面的播放条，但是无法暂停 及 调整播放进度

还有时候会出现点击播放，开始缓冲，但是无法播放的情况，但该情况可以关闭app，然后重启解决，复现步骤暂时未知。。但出现过好几次了。。。

**Comment by xioxin** [comment]
嗯 我看看

**Comment by byuan04** [comment]
貌似是直接通过命令行部署后
git clone https://github.com/xioxin/biliATV.git
cd biliATV && sh build.sh

默认子工程没有关联到最新
刚刚用sourcetree关联了下子工程最新代码貌似就正常了

**Comment by a211212abc** [comment]
@byuan04 求问子工程如何关联到最新呢

**Comment by xioxin** [comment]
cd 到对应目录 git pull

发自我的 iPhone

**Comment by a211212abc** [comment]
@xioxin 多谢！
