### ISSUE TITLE
免费账户没有tvos app的开发证书是么？

### ISSUE THREAD

**Issue by der035** [xioxin/biliATV#23]
![image](https://user-images.githubusercontent.com/42846823/44870410-8688f680-acd3-11e8-970b-6be4e6e4fa39.png)
无法运行 缺少权限
一定要付费账户才可以运行么，不想enroll之后还是不能运行

![image](https://user-images.githubusercontent.com/42846823/44870469-bd5f0c80-acd3-11e8-9772-654100839318.png)
l另外有这么多错误是正常的吗

**Comment by xioxin** [comment]
吧应用id修改下

**Comment by Xummer** [comment]
@xioxin 我能拿 biliATV 发个 TestFlight 么？如果想用的直接申请 TF 就好了😂

**Comment by xioxin** [comment]
使用私有api不知道能不能发TestFlight , 这个项目可以随意使用 不需要经过我的同意

**Comment by Xummer** [comment]
有特殊的上线技巧

**Comment by xioxin** [comment]
你有coding的账号吗?

**Comment by Xummer** [comment]
有的

**Comment by der035** [comment]
居然回复了诶，谢谢您
![image](https://user-images.githubusercontent.com/42846823/44902964-ab6e7f80-ad4e-11e8-9ae0-8ad9da666448.png)
还有这个是什么啊，还是无法运行 是不是哪里的文件权限有问题

**Comment by Xummer** [comment]
@der035 请更新最新的代码再尝试，或者直接更新 DaMuPlayer 到最新版本，具体原因请看这个 [commit](https://github.com/xioxin/biliATV/commit/64121ebd4fd2d54baaa11fb805b406bb8cb9e0ca)

**Comment by der035** [comment]
谢谢🙏 刚把这一行拿掉跑起来了
