### ISSUE TITLE
关于新版bilibili 接口解析

### ISSUE THREAD

**Issue by xioxin** [xioxin/biliATV#24]
bilibili新版解析直接把 url写在了html页面中 解析异常简单
也不需要UiWebView

**Comment by xioxin** [comment]
几乎移除了之前所有的swift部分的代码 简单写了个实验性的解析js的
dev分支 可以跑 不过功能不完整 

并且有概率报错 偶尔会不返回durl 而是返回一个dash_mpd 里面是xml格式文本 可能是灰度测试

**Comment by xioxin** [comment]
ios 下 cookie 是系统管理的 扫码登陆后 请求接口是自动附带上cookie的

**Comment by Xummer** [comment]
看来还是得去逆向下 B 站 app 😂

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/44946429-c1ec0800-ae2e-11e8-89d1-a28591bf2f5c.png)

 可以看到 已关注 状态是能获取到的 账号是正常登陆了的

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/44946475-9a496f80-ae2f-11e8-9d24-177d2c9e5354.png)
啊 哈 搞定了 
设置了下cookie 

```
        var cookieProperties = [HTTPCookiePropertyKey: String]()
        cookieProperties[HTTPCookiePropertyKey.name] = "CURRENT_QUALITY" as String
        cookieProperties[HTTPCookiePropertyKey.value] = "112" as String
        cookieProperties[HTTPCookiePropertyKey.domain] = ".bilibili.com" as String
        cookieProperties[HTTPCookiePropertyKey.path] = "/" as String
        let cookie = HTTPCookie(properties: cookieProperties)
        HTTPCookieStorage.shared.setCookie(cookie!)
```

**Comment by xioxin** [comment]
已经传到 dev分支

**Comment by xioxin** [comment]
现在这个分支还不能用 番剧暂时不能用

**Comment by xioxin** [comment]
番剧还是需要之前的方案 利用UiWebView 抓去 playurl 信息

**Comment by mengxingshifendeni** [comment]
使用原来的uiwebview貌似只能获得到自动清晰度的分辨率？

**Comment by Xummer** [comment]
@xioxin GJ

**Comment by xioxin** [comment]
@mengxingshifendeni  通过设置cookie可以修改清晰度 网页前端会检查浏览器是否支持flv解码 需要加载页面时候注入代码 伪造检查接口 才能加载高分辨率

**Comment by mengxingshifendeni** [comment]
@xioxin 请问是用的canplaytype这种方法检测支持么？通过伪造ui来避开检测？

**Comment by xioxin** [comment]
没明白什么意思

**Comment by frogcjn** [comment]
番剧页面master无法使用，点击无响应

**Comment by xjbeta** [comment]
cookies 获取durl 已失效
只能获取到视频 音频分离开来的json 但是可以选择清晰度
