### ISSUE TITLE
Emmm...每次启动都提示异常，然后就要扫码重新登陆

### ISSUE THREAD

**Issue by byuan04** [xioxin/biliATV#8]
第一天开着，第二天再使用就报异常要重新扫码登陆。。。

每天如此。。。

**Comment by YEZENING** [comment]
请问您在安装时有出现DanMuPlayer. h file not found 的情况么？

**Comment by fuzhuo** [comment]
网页扫码登录的Cookie只有一天有效期…

**Comment by xioxin** [comment]
原来是这样 😂

**Comment by fuzhuo** [comment]
@xioxin 来重写一把吧，这个项目很赞
https://github.com/xchaoinfo/fuck-login/blob/master/019%20bilibili/bilibili.py

**Comment by xioxin** [comment]
谢谢🙏 晚上看看

**Comment by xioxin** [comment]
@fuzhuo b站验证码换了 这个方法已经行不通了
