### ISSUE TITLE
小白安装：swift compiler erro

### ISSUE THREAD

**Issue by YEZENING** [xioxin/biliATV#9]
在安装biliATV的时候弹出DanMuPlayer.h file not found, 
请问一下这个应该如何解决呢？

**Comment by xioxin** [comment]
执行 build.sh 了吗

**Comment by YEZENING** [comment]
我认为已经执行了
#import <DanMuPlayer.h> file not found;

1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/zeningye/Library/Developer/Xcode/DerivedData/biliATV-dvgmatlgrfaemuaukzmotznjiqdg/Build/Intermediates.noindex/PrecompiledHeaders/Bridging-Header-swift_2IGPV3DX9DS1W-clang_1BJLXXMPNCLFD.pch' for bridging header '/Users/zeningye/Documents/Xcode/biliATV/biliATV/Bridging-Header.h'

**Comment by YEZENING** [comment]
小白表示更新后还是以上的问题。。。
我是缺了什么文件么？

**Comment by xioxin** [comment]
看一下你的文件结构 
![image](https://user-images.githubusercontent.com/5716100/35366103-b26edc46-01b2-11e8-9ffe-4960b29fbc2c.png)
这个文件在这里 如果不一样 你截张图我看看

**Comment by YEZENING** [comment]
发现问题了是缺少DanMuPlayer.xcodeproj文件，可是每次我克隆的时候都没有出现这个文件而且都是显示红色的。
<img width="275" alt="screen shot 2018-01-24 at 20 39 18" src="https://user-images.githubusercontent.com/24925677/35366298-c0f6a04e-0146-11e8-8dff-bafd96bbd092.png">

**Comment by YEZENING** [comment]
这个是从您的界面上克隆下来的整个文件，每次我查看都是缺少DanMuPlayer整个文件

**Comment by xioxin** [comment]
执行 build.sh 它会自动下载

**Comment by YEZENING** [comment]
这样啊，应该怎么执行呢？

**Comment by xioxin** [comment]
终端知道吧
进入到 biliATV目录
执行 sh build.sh

**Comment by YEZENING** [comment]
OK我试试
